[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SummationByParts = "55d25451-638a-4804-8089-59924bcb4a40"
